import React, { useRef, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Animated,
  Pressable,
} from 'react-native';
import { useRouter } from 'expo-router';
import { X } from 'lucide-react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Colors } from '@/constants/colors';

const EFFECTIVE_DATE = 'February 26, 2026';
const APP_NAME = 'Emperial Bot';
const COMPANY_NAME = 'Emperial Solutions International, L.L.C.';

interface Section {
  heading: string;
  body: string;
}

const TERMS_SECTIONS: Section[] = [
  {
    heading: '1. Acceptance of Terms',
    body: `By downloading, installing, accessing, or using ${APP_NAME} (the "Application"), you ("User," "you," or "your") acknowledge that you have read, understood, and agree to be legally bound by these Terms and Conditions ("Terms"), our Privacy Policy, and any supplemental terms, policies, or disclaimers posted within the Application. If you do not agree to these Terms in their entirety, you must immediately cease all use of the Application and delete it from your device(s).

These Terms constitute a legally binding agreement between you and ${COMPANY_NAME} ("Company," "we," "us," or "our"). Your continued use of the Application after any modification to these Terms constitutes acceptance of such modifications. We reserve the right to update these Terms at any time without prior notice; the most current version shall always be available within the Application.`,
  },
  {
    heading: '2. Eligibility and Account Requirements',
    body: `You must be at least 18 years of age (or the age of majority in your jurisdiction, whichever is greater) to use the Application. By using the Application, you represent and warrant that you meet this age requirement and have the legal capacity to enter into a binding agreement.

You are solely responsible for maintaining the confidentiality and security of your account credentials, API keys, passwords, and any other authentication mechanisms. You agree to immediately notify us of any unauthorized use of your account. We shall not be liable for any loss or damage arising from your failure to safeguard your credentials.

You acknowledge that certain features require connection to third-party brokerage accounts, exchanges, or financial platforms. You are solely responsible for compliance with all terms, policies, and regulatory requirements imposed by such third-party services.`,
  },
  {
    heading: '3. Nature of the Application — No Financial Advice',
    body: `THE APPLICATION IS A SOFTWARE TOOL THAT PROVIDES MARKET DATA VISUALIZATION, TECHNICAL ANALYSIS INDICATORS, AUTOMATED TRADING BOT CAPABILITIES, SIGNAL ALERTS, AND BROKER INTEGRATION FEATURES. THE APPLICATION DOES NOT CONSTITUTE, AND SHALL NOT BE CONSTRUED AS, FINANCIAL ADVICE, INVESTMENT ADVICE, TRADING ADVICE, TAX ADVICE, LEGAL ADVICE, OR ANY OTHER FORM OF PROFESSIONAL ADVISORY SERVICE.

All information, data, signals, scores, indicators, and outputs generated by the Application (including but not limited to composite scores, buy/sell signals, bot trading recommendations, arbitrage opportunities, and alert triggers) are provided for informational and educational purposes only. No content within the Application constitutes a solicitation, recommendation, endorsement, or offer to buy or sell any financial instrument, security, cryptocurrency, commodity, futures contract, or derivative product.

You expressly acknowledge and agree that:
(a) All trading and investment decisions are made solely at your own risk and discretion;
(b) Past performance of any indicator, strategy, bot, or signal is not indicative of future results;
(c) You should consult with a qualified, licensed financial advisor before making any investment decisions;
(d) The Company does not act as a broker, dealer, investment advisor, or fiduciary in any capacity.`,
  },
  {
    heading: '4. AI Technology Disclosure and Limitations',
    body: `The Application incorporates artificial intelligence ("AI") and machine learning technologies in various features including, but not limited to, signal generation, pattern recognition, trading bot decision-making, composite score calculation, arbitrage detection, and alert systems.

YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT:

(a) AI-Generated Outputs Are Not Guaranteed: AI and machine learning models are probabilistic in nature. Outputs, predictions, signals, and recommendations generated by AI components may be inaccurate, incomplete, misleading, or entirely incorrect. No representation or warranty is made regarding the accuracy, reliability, completeness, or timeliness of any AI-generated output.

(b) AI Hallucination and Error Risk: AI systems may produce outputs that appear plausible but are factually incorrect ("hallucinations"). The Company disclaims all liability for decisions made in reliance on AI-generated content.

(c) No Autonomous Financial Decision-Making: While the Application includes automated trading bot functionality, all automated actions are initiated based on user-configured parameters. The User bears full responsibility for configuring, monitoring, supervising, and controlling all automated trading activities.

(d) Model Limitations: AI models are trained on historical data and may not adequately account for unprecedented market conditions, black swan events, regulatory changes, flash crashes, liquidity crises, or other anomalous events.

(e) Continuous Evolution: AI models and algorithms may be updated, retrained, or modified at any time without notice. Such changes may alter the behavior, accuracy, or outputs of AI-driven features.

(f) No Fiduciary Duty: The use of AI technology does not create any fiduciary, advisory, or professional relationship between the Company and the User.

(g) Bias and Data Dependency: AI outputs are dependent on the quality, completeness, and timeliness of input data. Data feed interruptions, API failures, exchange outages, or corrupted data may result in erroneous AI outputs.

(h) Regulatory Compliance: The User is solely responsible for ensuring that their use of AI-assisted trading features complies with all applicable laws, regulations, and exchange rules in their jurisdiction, including but not limited to regulations governing algorithmic trading, market manipulation, and automated order execution.`,
  },
  {
    heading: '5. Automated Trading and Bot Services',
    body: `The Application provides automated trading bot functionality that can execute trades on connected brokerage and exchange accounts based on user-defined parameters and strategies.

YOU ACKNOWLEDGE AND AGREE THAT:

(a) Financial Risk: Automated trading carries substantial risk of financial loss, including the potential loss of your entire invested capital. Leveraged trading products (futures, margin, derivatives) amplify both gains and losses.

(b) User Responsibility: You are solely responsible for all trades executed by automated bots, whether profitable or unprofitable. The Company has no control over and assumes no responsibility for the execution, timing, price, or outcome of any trade.

(c) Technical Failures: Automated trading systems may be affected by software bugs, connectivity issues, API rate limits, exchange downtime, latency, slippage, partial fills, market gaps, circuit breakers, and other technical factors that may result in unintended trades, failed executions, or financial losses.

(d) No Guarantee of Performance: The Company makes no guarantees regarding the profitability, performance, or reliability of any trading bot, strategy, or algorithm provided within the Application.

(e) Paper Trading vs. Live Trading: Users should thoroughly test all bot configurations using paper trading mode before enabling live trading. The Company strongly recommends extended paper trading periods to validate strategy performance.

(f) Kill Switch and Monitoring: You agree to actively monitor all automated trading activity and maintain the ability to immediately disable any bot or revoke API access at any time. Failure to monitor automated systems does not relieve you of responsibility for resulting trades or losses.`,
  },
  {
    heading: '6. Third-Party Services and Broker Integrations',
    body: `The Application facilitates integration with third-party services including but not limited to TradingView, NinjaTrader, Rithmic (R-Pro Trader), Binance, Binance.US, and other brokerages, exchanges, and data providers ("Third-Party Services").

(a) Independent Services: Third-Party Services are operated by independent entities not controlled by or affiliated with the Company. Your use of Third-Party Services is governed by their respective terms of service, privacy policies, and applicable regulations.

(b) No Endorsement: Integration with or reference to any Third-Party Service does not constitute an endorsement, recommendation, or guarantee by the Company.

(c) API Key Risk: Providing API keys to the Application grants it programmatic access to your third-party accounts. While API keys are stored locally on your device, you acknowledge the inherent risks of API-based access, including unauthorized use, key compromise, and unintended trade execution. The Company recommends restricting API key permissions (e.g., disabling withdrawal capabilities) and implementing IP whitelisting where available.

(d) No Liability for Third-Party Actions: The Company shall not be liable for any actions, omissions, outages, data breaches, or losses arising from or related to Third-Party Services.

(e) Webhook and Data Transmission: Data transmitted via webhooks, APIs, or other integration mechanisms may traverse public networks and third-party infrastructure. The Company does not guarantee the confidentiality, integrity, or delivery of such transmissions.`,
  },
  {
    heading: '7. Data Accuracy and Market Data',
    body: `(a) No Warranty of Accuracy: Market data, price feeds, indicators, technical analysis outputs, and all other data displayed within the Application are provided on an "AS IS" and "AS AVAILABLE" basis. The Company makes no warranty regarding the accuracy, completeness, timeliness, or reliability of any data.

(b) Data Sources: Data is sourced from third-party providers including exchange APIs, public market feeds, and calculated datasets. Data may be delayed, incomplete, or erroneous due to factors beyond the Company's control.

(c) Simulated Data: Certain instruments may utilize simulated or estimated data when live feeds are unavailable. Simulated data is clearly marked where feasible but may not always be distinguishable from live data.

(d) Indicator Calculations: Technical indicator values are calculated based on available candle/bar data and standard mathematical formulas. Variations in data sources, timestamps, or calculation methodologies may produce results that differ from other platforms.

(e) Critical Decision Verification: You must independently verify all data, signals, and indicators with your broker's platform or other authoritative sources before making any trading or investment decisions.`,
  },
  {
    heading: '8. Intellectual Property',
    body: `(a) Ownership: The Application, including all software, source code, algorithms, AI models, trading strategies, user interface designs, graphics, logos, the "Emperial Bot" name and brand, trademarks, trade secrets, and all associated content, is the exclusive intellectual property of ${COMPANY_NAME} (the "Rights Holder"). The Application is protected by copyright, trademark, trade secret, patent, and other intellectual property laws of the United States and international treaties. Any individual previously associated with this project, including but not limited to Tony Groves, is permanently barred from any ownership claim, usage right, distribution right, or financial benefit derived from this software.

(b) No Transfer of Rights: No rights, title, or interest in the Application or any intellectual property contained therein is transferred to any user or third party by virtue of downloading, installing, accessing, or using the Application. All rights not expressly granted herein are reserved by the Rights Holders.

(c) Limited License: Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to use the Application on your personal device(s) for lawful, personal, non-commercial purposes (unless a commercial license is obtained). This license may be revoked at any time, with or without cause.

(d) Restrictions: You shall not: (i) copy, modify, adapt, translate, reverse engineer, decompile, disassemble, or attempt to derive the source code of any portion of the Application; (ii) create derivative works based on the Application; (iii) distribute, sublicense, lease, rent, loan, or otherwise transfer the Application to any third party; (iv) use the Application to develop competing products or services; (v) remove, alter, or obscure any proprietary notices, labels, or marks; (vi) use any automated means (scraping, crawling, etc.) to access the Application or extract data; (vii) claim ownership of, or any rights to, the Application, its code, brand, or any component thereof; (viii) attempt to circumvent any security, authentication, or licensing mechanisms within the Application.

(e) Enforcement: The Rights Holder reserves the right to pursue all available legal remedies, including injunctive relief, damages, and criminal prosecution, against any individual or entity that infringes upon or misappropriates the intellectual property of the Application.

(f) Prohibited Parties: Tony Groves is expressly and permanently prohibited from claiming any ownership, development credit, licensing rights, distribution rights, or financial benefit from this software or any derivative thereof. Any attempt to do so constitutes theft of intellectual property and will result in immediate legal action under applicable U.S. federal and state law.`,
  },
  {
    heading: '9. Subscription, Payments, and Refunds',
    body: `(a) Subscription Plans: Certain features of the Application require a paid subscription. Subscription plans, pricing, and feature access are described within the Application and may change at any time.

(b) Billing: Subscriptions are billed through the Apple App Store, Google Play Store, or other authorized distribution platforms ("Platform"). All billing, payment processing, and refund policies are governed by the respective Platform's terms.

(c) Auto-Renewal: Subscriptions automatically renew at the end of each billing period unless cancelled at least 24 hours before the renewal date through your Platform account settings.

(d) No Refunds: To the maximum extent permitted by applicable law, all purchases are final and non-refundable. Refund requests must be directed to the respective Platform.

(e) Price Changes: We reserve the right to modify subscription pricing at any time. Existing subscribers will be notified of price changes before their next renewal period.

(f) Lifetime Plans: Lifetime subscription plans grant access for the operational lifetime of the Application. "Lifetime" refers to the commercially viable lifespan of the product, not the lifetime of the User. The Company reserves the right to define and modify the scope of lifetime access.`,
  },
  {
    heading: '10. Automated Trade Interest Charge — 1% Service Fee',
    body: `BY USING THE AUTOMATED TRADING BOT FEATURES OF ${APP_NAME}, YOU EXPRESSLY ACKNOWLEDGE, AGREE TO, AND ACCEPT THE FOLLOWING SERVICE FEE TERMS:

(a) 1% Interest Charge: ${COMPANY_NAME} shall charge a one percent (1%) interest fee ("Service Fee") on the gross value of every trade executed automatically by the ${APP_NAME} trading bot system. This Service Fee applies to all automatic trades regardless of whether the trade results in a profit or a loss.

(b) Calculation Basis: The 1% Service Fee is calculated based on the total notional value (gross execution value) of each individual automated trade at the time of execution. For example, if an automated trade is executed with a notional value of $10,000, a Service Fee of $100 (1% × $10,000) shall be assessed.

(c) Applicability: The Service Fee applies exclusively to trades initiated and executed by the ${APP_NAME} automated trading bot system, including but not limited to: algorithmic trades, signal-triggered executions, arbitrage trades, and any other order placed programmatically by the bot on your behalf through connected broker accounts or exchanges.

(d) Collection Method: The Service Fee may be collected through one or more of the following methods, at the Company's sole discretion: (i) automatic deduction from your connected brokerage or exchange account balance; (ii) periodic invoicing and billing to your registered payment method; (iii) deduction from trade proceeds prior to settlement; or (iv) any other commercially reasonable collection method. The Company will provide transparent accounting of all Service Fees assessed.

(e) Fee Accrual and Reporting: All Service Fees accrue at the time of trade execution. A detailed record of all Service Fees charged will be available within the Application's trading history and account dashboard. You agree to review your fee statements regularly and report any discrepancies within thirty (30) days of the fee being assessed.

(f) Fee Adjustments: The Company reserves the right to modify the Service Fee percentage at any time upon thirty (30) days' prior written notice to active subscribers. Continued use of the automated trading features after the effective date of any fee change constitutes acceptance of the revised fee.

(g) No Fee for Manual Trades: The 1% Service Fee does not apply to trades placed manually by the User through the Application's interface or directly through their broker/exchange platform. The fee applies solely to trades executed by the automated bot system.

(h) Tax Responsibility: The User is solely responsible for all tax obligations arising from trading activity and the payment of Service Fees, including any applicable sales tax, value-added tax (VAT), or withholding tax on the Service Fee itself.

(i) Fee Disputes: Any disputes regarding the calculation or assessment of Service Fees must be submitted in writing to billing@emperialbot.com within thirty (30) days of the disputed fee. Failure to dispute a fee within this period constitutes acceptance and waiver of any right to contest the charge.

(j) Acknowledgment of Fee Impact: You acknowledge that the 1% Service Fee will reduce the net profitability of automated trades and increase the effective cost of automated trading activity. You have independently evaluated the impact of this fee on your trading strategy and accept it as a condition of using the automated trading features.`,
  },
  {
    heading: '11. Privacy and Data Collection',
    body: `Your use of the Application is also governed by our Privacy Policy, which describes how we collect, use, store, and protect your information. By using the Application, you consent to the data practices described in the Privacy Policy.

(a) Local Storage: API keys, credentials, and sensitive configuration data are stored locally on your device. The Company does not transmit or store your API keys on remote servers.

(b) Analytics: We may collect anonymized usage analytics to improve the Application. No personally identifiable financial data or trading history is collected without explicit consent.

(c) Data Security: While we implement commercially reasonable security measures, no method of electronic storage or transmission is 100% secure. The Company cannot guarantee absolute security of your data.`,
  },
  {
    heading: '12. Disclaimer of Warranties',
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APPLICATION IS PROVIDED "AS IS," "AS AVAILABLE," AND "WITH ALL FAULTS." THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO:

(a) IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT;
(b) WARRANTIES ARISING FROM COURSE OF DEALING, USAGE, OR TRADE PRACTICE;
(c) WARRANTIES THAT THE APPLICATION WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR HARMFUL COMPONENTS;
(d) WARRANTIES REGARDING THE ACCURACY, RELIABILITY, TIMELINESS, OR COMPLETENESS OF ANY DATA, CONTENT, OR INFORMATION;
(e) WARRANTIES THAT THE APPLICATION WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS;
(f) WARRANTIES REGARDING THE RESULTS OBTAINED FROM USE OF THE APPLICATION;
(g) WARRANTIES REGARDING THE PERFORMANCE OR ACCURACY OF ANY AI, MACHINE LEARNING, OR ALGORITHMIC COMPONENT.

NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM THE COMPANY OR THROUGH THE APPLICATION SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.`,
  },
  {
    heading: '13. Limitation of Liability',
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:

(a) IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, SUCCESSORS, OR ASSIGNS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO: LOSS OF PROFITS, LOSS OF DATA, LOSS OF GOODWILL, TRADING LOSSES, FINANCIAL LOSSES, LOSS OF BUSINESS OPPORTUNITIES, LOSS OF ANTICIPATED SAVINGS, OR ANY OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE APPLICATION, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE) AND EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

(b) THE COMPANY'S TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR THE APPLICATION SHALL NOT EXCEED THE GREATER OF: (I) THE AMOUNT YOU PAID TO THE COMPANY IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (II) ONE HUNDRED U.S. DOLLARS ($100.00).

(c) THE LIMITATIONS IN THIS SECTION APPLY TO ALL CLAIMS, WHETHER BASED ON WARRANTY, CONTRACT, TORT, STATUTE, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY HAS BEEN INFORMED OF THE POSSIBILITY OF ANY SUCH DAMAGE.

(d) CERTAIN JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY, AND YOU MAY HAVE ADDITIONAL RIGHTS.`,
  },
  {
    heading: '14. Indemnification',
    body: `You agree to indemnify, defend, and hold harmless ${COMPANY_NAME}, its officers, directors, employees, contractors, agents, affiliates, successors, and assigns from and against any and all claims, demands, actions, suits, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees, expert fees, and court costs) arising out of or related to:

(a) Your use or misuse of the Application;
(b) Your violation of these Terms or any applicable law, regulation, or third-party right;
(c) Your trading activities, including all trades executed manually or through automated bots;
(d) Your use of third-party broker integrations and API connections;
(e) Any content, data, or information you submit, transmit, or make available through the Application;
(f) Your negligence, willful misconduct, or fraud;
(g) Any claim that your use of the Application caused damage to a third party.

This indemnification obligation shall survive the termination of these Terms and your use of the Application.`,
  },
  {
    heading: '15. Assumption of Risk',
    body: `BY USING THE APPLICATION, YOU EXPRESSLY ACKNOWLEDGE AND ASSUME ALL RISKS ASSOCIATED WITH:

(a) Trading in financial markets, including the risk of total loss of invested capital;
(b) Use of automated trading systems and algorithmic strategies;
(c) Reliance on AI-generated signals, scores, indicators, and recommendations;
(d) Integration with third-party brokerages, exchanges, and financial platforms;
(e) Transmission of data, API keys, and credentials over electronic networks;
(f) Market volatility, liquidity risk, gap risk, slippage, and execution risk;
(g) Regulatory changes that may affect the legality or availability of certain trading activities or instruments in your jurisdiction;
(h) Technological failures, including software bugs, connectivity issues, exchange outages, and cybersecurity threats;
(i) The inherent limitations and potential errors of AI and machine learning technologies.

You represent that you have sufficient knowledge, experience, and financial resources to evaluate and bear the risks associated with trading and the use of this Application. You acknowledge that the Company has not made and does not make any representations regarding the potential profitability of any trading activity.`,
  },
  {
    heading: '16. Dispute Resolution and Arbitration',
    body: `(a) Binding Arbitration: Any dispute, claim, or controversy arising out of or relating to these Terms or the Application shall be resolved through binding arbitration administered by the American Arbitration Association ("AAA") in accordance with its Commercial Arbitration Rules, rather than in court, except that either party may seek injunctive or equitable relief in a court of competent jurisdiction.

(b) Class Action Waiver: YOU AND THE COMPANY AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, CONSOLIDATED, OR REPRESENTATIVE ACTION. The arbitrator may not consolidate more than one person's claims and may not preside over any form of class or representative proceeding.

(c) Arbitration Location: Arbitration shall take place in the State of Delaware, United States, or at another mutually agreed-upon location.

(d) Arbitration Fees: Each party shall bear its own costs and fees associated with arbitration. If the arbitrator determines that a claim is frivolous, the non-prevailing party shall reimburse the other party for its reasonable fees and costs.

(e) Small Claims Exception: Notwithstanding the foregoing, either party may bring a qualifying claim in small claims court.

(f) Statute of Limitations: Any claim arising out of or related to these Terms must be filed within one (1) year after the cause of action accrues. Claims filed after this period are permanently barred.`,
  },
  {
    heading: '17. Governing Law and Jurisdiction',
    body: `These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law principles. To the extent that arbitration is not applicable, you consent to the exclusive jurisdiction and venue of the state and federal courts located in the State of Delaware for the resolution of any disputes.`,
  },
  {
    heading: '18. Termination',
    body: `(a) By You: You may terminate your use of the Application at any time by deleting it from your device(s) and discontinuing all use. Active subscriptions must be cancelled through the respective Platform.

(b) By Us: We may suspend or terminate your access to the Application at any time, with or without cause, and with or without notice. Grounds for termination include, but are not limited to: violation of these Terms, fraudulent activity, abusive behavior, or actions that may harm the Company, other users, or third parties.

(c) Effect of Termination: Upon termination, all rights and licenses granted to you under these Terms shall immediately cease. Sections that by their nature should survive termination (including Disclaimer of Warranties, Limitation of Liability, Indemnification, Assumption of Risk, Dispute Resolution, and Governing Law) shall survive.`,
  },
  {
    heading: '19. Force Majeure',
    body: `The Company shall not be liable for any failure or delay in performance resulting from causes beyond its reasonable control, including but not limited to: acts of God, natural disasters, pandemics, epidemics, war, terrorism, riots, embargoes, acts of governmental authorities, fire, flood, accidents, strikes, labor disputes, power failures, internet or telecommunications failures, exchange outages, cyberattacks, or any other event beyond the Company's reasonable control.`,
  },
  {
    heading: '20. Severability',
    body: `If any provision of these Terms is found to be invalid, illegal, or unenforceable by a court of competent jurisdiction or arbitrator, such finding shall not affect the validity or enforceability of the remaining provisions, which shall continue in full force and effect. The invalid or unenforceable provision shall be modified to the minimum extent necessary to make it valid and enforceable while preserving the original intent of the parties.`,
  },
  {
    heading: '21. Entire Agreement',
    body: `These Terms, together with the Privacy Policy and any supplemental terms or policies referenced herein, constitute the entire agreement between you and the Company regarding the subject matter hereof and supersede all prior or contemporaneous understandings, agreements, negotiations, representations, and warranties, both written and oral, regarding such subject matter.`,
  },
  {
    heading: '22. Waiver',
    body: `No failure or delay by the Company in exercising any right, power, or remedy under these Terms shall operate as a waiver thereof. No single or partial exercise of any right, power, or remedy shall preclude any other or further exercise thereof or the exercise of any other right, power, or remedy. The rights and remedies provided herein are cumulative and not exclusive of any rights or remedies provided by law.`,
  },
  {
    heading: '23. Assignment',
    body: `You may not assign, delegate, or transfer these Terms or any rights or obligations hereunder without the prior written consent of the Company. The Company may freely assign these Terms and its rights and obligations hereunder to any successor in interest of any business associated with the Application, whether by merger, acquisition, reorganization, or otherwise. These Terms shall be binding upon and inure to the benefit of the parties, their successors, and permitted assigns.`,
  },
  {
    heading: '24. Electronic Communications',
    body: `By using the Application, you consent to receive electronic communications from the Company, including but not limited to: in-app notifications, push notifications, email communications, and updates to these Terms. You agree that all agreements, notices, disclosures, and other communications provided to you electronically satisfy any legal requirement that such communications be in writing.`,
  },
  {
    heading: '25. Export Controls and Sanctions Compliance',
    body: `You agree to comply with all applicable export control laws, trade sanctions, and import laws of the United States and any other applicable jurisdiction. You represent and warrant that you are not located in, under the control of, or a national or resident of any country subject to U.S. economic sanctions, and that you are not on any U.S. government list of prohibited or restricted parties.`,
  },
  {
    heading: '26. Compliance with Laws',
    body: `You are solely responsible for ensuring that your use of the Application complies with all applicable local, state, national, and international laws, rules, and regulations, including but not limited to securities laws, commodity trading regulations, anti-money laundering ("AML") requirements, know your customer ("KYC") obligations, tax reporting obligations, and any laws governing the use of AI and algorithmic trading in your jurisdiction.

The availability of the Application does not constitute an offer or solicitation in any jurisdiction where such offer or solicitation would be unlawful.`,
  },
  {
    heading: '27. Contact Information',
    body: `If you have any questions, concerns, or complaints regarding these Terms or the Application, please contact us at:

${COMPANY_NAME}
Email: legal@emperialbot.com
Subject: Terms and Conditions Inquiry

For urgent security concerns regarding API keys or account compromise, please contact: security@emperialbot.com`,
  },
];

export default function TermsScreen() {
  const fadeAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 400,
      useNativeDriver: true,
    }).start();
  }, [fadeAnim]);

  const router = useRouter();
  const insets = useSafeAreaInsets();

  return (
    <Animated.View style={[styles.root, { opacity: fadeAnim }]}>
      <View style={[styles.header, { paddingTop: insets.top + 8 }]}>
        <Text style={styles.headerTitle}>Terms & Conditions</Text>
        <Pressable
          onPress={() => router.back()}
          style={({ pressed }) => [styles.closeBtn, pressed && { opacity: 0.6 }]}
          hitSlop={12}
          testID="terms-close-btn"
        >
          <X size={20} color={Colors.text} />
        </Pressable>
      </View>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.bannerCard}>
          <Text style={styles.bannerTitle}>Terms & Conditions</Text>
          <Text style={styles.bannerSubtitle}>
            Effective Date: {EFFECTIVE_DATE}
          </Text>
          <View style={styles.bannerDivider} />
          <Text style={styles.bannerNote}>
            Please read these Terms and Conditions carefully before using {APP_NAME}. By accessing or using the Application, you agree to be bound by these Terms.
          </Text>
        </View>

        {TERMS_SECTIONS.map((section, index) => (
          <View key={index} style={styles.sectionCard}>
            <Text style={styles.sectionHeading}>{section.heading}</Text>
            <Text style={styles.sectionBody}>{section.body}</Text>
          </View>
        ))}

        <View style={styles.footerCard}>
          <View style={styles.footerAccent} />
          <Text style={styles.footerText}>
            Last Updated: {EFFECTIVE_DATE}
          </Text>
          <Text style={styles.footerSub}>
            {COMPANY_NAME} — All Rights Reserved
          </Text>
          <Text style={styles.footerDisclaimer}>
            By continuing to use {APP_NAME}, you acknowledge and accept these Terms and Conditions in their entirety.
          </Text>
        </View>
      </ScrollView>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Colors.bg0,
  },
  header: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: Colors.white,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.bg2,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 14,
    paddingBottom: 120,
    gap: 10,
  },
  bannerCard: {
    backgroundColor: Colors.bg1,
    borderRadius: 14,
    padding: 18,
    borderWidth: 1,
    borderColor: Colors.amber + '30',
  },
  bannerTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: Colors.amber,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  bannerSubtitle: {
    fontSize: 13,
    color: Colors.text2,
    fontWeight: '600' as const,
    marginBottom: 12,
  },
  bannerDivider: {
    height: 1,
    backgroundColor: Colors.amber + '20',
    marginBottom: 12,
  },
  bannerNote: {
    fontSize: 13,
    color: Colors.text,
    lineHeight: 20,
  },
  sectionCard: {
    backgroundColor: Colors.bg1,
    borderRadius: 12,
    padding: 16,
    borderWidth: 0.5,
    borderColor: Colors.border,
  },
  sectionHeading: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: Colors.text,
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  sectionBody: {
    fontSize: 13,
    color: Colors.text2,
    lineHeight: 21,
  },
  footerCard: {
    backgroundColor: Colors.bg1,
    borderRadius: 14,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    marginTop: 8,
  },
  footerAccent: {
    width: 40,
    height: 3,
    borderRadius: 2,
    backgroundColor: Colors.amber,
    opacity: 0.5,
    marginBottom: 14,
  },
  footerText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: Colors.text2,
    letterSpacing: 0.3,
  },
  footerSub: {
    fontSize: 12,
    color: Colors.text3,
    marginTop: 4,
  },
  footerDisclaimer: {
    fontSize: 11,
    color: Colors.text3,
    marginTop: 12,
    textAlign: 'center',
    lineHeight: 17,
  },
});
